use crate::graphics::context::{AppTab, PacketFilterProfile, PacketTrigger};
use crate::ui::notification_manager::NotificationManager;

#[allow(clippy::too_many_arguments)]
pub struct UiState<'a> {
    pub new_username: &'a mut String,
    pub new_player_id: &'a mut String,
    pub new_access_token: &'a mut String,
    pub new_session_type: &'a mut String,
    pub notification_manager: &'a NotificationManager,
    pub clipboard: &'a mut crate::input::clipboard::ClipboardManager,
    pub selected_tab: &'a mut AppTab,
    pub account_name_input: &'a mut String,
    pub selected_account: &'a mut Option<String>,
    pub show_manual_input_dialog: &'a mut bool,
    pub manual_account_name: &'a mut String,
    pub manual_username: &'a mut String,
    pub manual_player_id: &'a mut String,
    pub manual_access_token: &'a mut String,
    pub manual_session_type: &'a mut String,
    pub manual_password: &'a mut String,
    pub show_edit_dialog: &'a mut bool,
    pub edit_account_name: &'a mut String,
    pub edit_username: &'a mut String,
    pub edit_player_id: &'a mut String,
    pub edit_access_token: &'a mut String,
    pub edit_session_type: &'a mut String,
    pub edit_password: &'a mut String,
    pub edit_original_name: &'a mut String,
    pub auth_in_progress: &'a mut bool,
    pub packet_filter: &'a mut String,
    pub packet_show_inbound: &'a mut bool,
    pub packet_show_outbound: &'a mut bool,
    pub packet_autoscroll: &'a mut bool,
    pub packet_paused: &'a mut bool,
    pub packets_detached: &'a mut bool,
    pub packets_window_open: &'a mut bool,
    pub selected_packet_id: &'a mut Option<u64>,
    pub packet_only_pinned: &'a mut bool,
    pub packet_limit_count: &'a mut u32,
    pub packet_autoclear_oldest: &'a mut bool,
    pub packet_filter_profiles: &'a mut Vec<PacketFilterProfile>,
    pub packet_profile_new_name: &'a mut String,
    pub packet_profile_new_query: &'a mut String,
    pub packet_show_only_new: &'a mut bool,
    pub packet_last_seen_id: &'a mut u64,
    pub packet_secondary_selected_id: &'a mut Option<u64>,
    pub packet_triggers: &'a mut Vec<PacketTrigger>,
    pub packet_trigger_input: &'a mut String,
    pub packet_tag_editor: &'a mut String,
    pub packet_color_hex: &'a mut String,
    pub packet_export_limit: &'a mut u32,
    pub packet_import_buffer: &'a mut String,

    pub search_query: &'a mut String,
    pub selected_class: &'a mut Option<String>,
    pub is_loading: &'a mut bool,
    pub error_message: &'a mut Option<String>,
    pub detached: &'a mut bool,
    pub window_open: &'a mut bool,
    pub expand_fields: &'a mut bool,
    pub expand_methods: &'a mut bool,
    pub member_search_query: &'a mut String,

    pub auth_tab_username: &'a mut String,
    pub auth_tab_password: &'a mut String,
    pub auth_tab_result_token: &'a mut String,
    pub auth_tab_result_profile: &'a mut String,
    pub auth_tab_in_progress: &'a mut bool,
    pub auth_tab_error: &'a mut Option<String>,
}
